/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package c;

import static c.Investment.InvestmentAll;
import javax.swing.JOptionPane;

/**
 *
 * @author mustafaasimcihan
 */
public class BuyInvestment extends javax.swing.JDialog {

    /**
     * Creates new form BuyInvestment
     */
    public BuyInvestment(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("    Buy an investment");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Stock", "Mutualfund" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter the investment kind");

        jLabel3.setText("Symbol");

        jLabel4.setText("Name");

        jLabel5.setText("Quantity");

        jLabel6.setText("Price");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jButton1.setText("Buy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4))
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        int checker = 0;
        
        int last = 0;
        
        String investKind = jComboBox1.getSelectedItem().toString().toLowerCase();
        
        
        String investSymbol = jTextField1.getText();
        
        if(investSymbol.isEmpty())
        
        {
        
            JOptionPane.showMessageDialog(null, "Symbol kind can not be empty");
            
            last = 1;
        
        }
        
        
        
        String investQuantity = jTextField3.getText();
        
        if(investQuantity.isEmpty())
        
        {
        
            JOptionPane.showMessageDialog(null, "Quantity can not be empty");
            
            last = 1;
        
        }
        
        if(!investQuantity.isEmpty())
        
        {
        
            try 
            
        {
            int num = 0;
            
            num = Integer.parseInt(investQuantity);
        
            //System.out.println(num);
        
        } 
        
        catch (NumberFormatException e) 
            
        {
            
            JOptionPane.showMessageDialog(null, "Quantity should be integer");
            
            jTextField3.setText("");
         
            last = 1;
        
        }
        
        }
        
        String investPrice = jTextField4.getText();
        
        if(investPrice.isEmpty())
        
        {
        
            JOptionPane.showMessageDialog(null, "Price can not be empty");
            
            last = 1;
        
        }
        
        if(!investPrice.isEmpty())
        
        {
        
            try 
            
        {
            double num = 0;
            
            num = Double.parseDouble(investPrice);
        
            //System.out.println(num);
        
        } 
        
        catch (NumberFormatException e) 
            
        {
            
            JOptionPane.showMessageDialog(null, "Price should be integer");
            
            jTextField4.setText("");
         
            last = 1;
        
        }
        
            
        
        }
        
        String investName = jTextField2.getText();
        
        if(investName.isEmpty())
        
        {
        
            JOptionPane.showMessageDialog(null, "Name can not be empty");
            
            last = 1;
        
        }
        
        
        
        if(investKind.equals("stock"))
                
                {
                    //System.out.println("Enter the symbol of stock");
                    
                    //aaa = scan.nextLine();
                    
                    
                            
                   for(Investment a : InvestmentAll)
               
                        {
                   
                            if(a.symbol.equals(investSymbol))
                            
                            {
                                int quantityForStock = 0;
                                
                                double newPriceForStock = 0;
                                
                                //System.out.println("Enter the quantity");
                                
                                quantityForStock = Integer.parseInt(investQuantity);
                                
                                //System.out.println("Enter the new price");
                                
                                newPriceForStock = Double.parseDouble(investPrice);
                                
                                //scan.nextLine();
                                
                                if(last == 0)
                                
                                {
                                
                                a.setPrice(newPriceForStock);
                                
                                a.setQuantity(quantityForStock);
                                
                                a.setBookValue(a.bookValue, newPriceForStock, quantityForStock,0);
                                
                                checker++;
                                
                                JOptionPane.showMessageDialog(null, "Succesfully bought");
                                
                                }
                                
                            }
                        }
                   
                    if(checker == 0)
                    
                    {
                            
                                String stockName;
                                
                                String stockSymbol;
                                
                                int stockQuantity = 0;
                                
                                double stockPrice = 0;
                            
                                //System.out.println("Enter the stock name");
                                
                                stockName = investName; 
                                
                                //System.out.println("Enter the symbol");
                                
                                stockSymbol = investSymbol;
                                
                                //System.out.println("Enter the quantity");
                                
                                stockQuantity = Integer.parseInt(investQuantity);
                                
                                //System.out.println("Enter the price");
                                
                                stockPrice = Double.parseDouble(investPrice);
                                
                                //scan.nextLine();
                                
                                if(last == 0)
                                
                                {
                                
                                Stock stocka  = new Stock(stockSymbol,stockName,stockQuantity,stockPrice,0);
                                
                                stocka.setBookValue(0,stockPrice, stockQuantity,0);
                                
                                InvestmentAll.add(stocka);
                                
                                JOptionPane.showMessageDialog(null, "Succesfully bought");
                                
                                
                                }
                    }
                                
               }
        
        if(investKind.equals("mutualfund"))
                
                {
                   //System.out.println("Enter the symbol");
                   
                   //bbb = scan.nextLine();
                   
                   for(Investment a : InvestmentAll)
               
                        {
                   
                            if(a.symbol.equals(investSymbol))
                            
                            {
                                int quantityForStock = 0;
                                
                                double newPriceForStock = 0;
                                
                                //System.out.println("Enter the quantity");
                                
                                quantityForStock = Integer.parseInt(investQuantity);
                                
                                //System.out.println("Enter the new price");
                                
                                newPriceForStock = Double.parseDouble(investPrice);
                                
                                //scan.nextLine();
                                
                                if(last == 0)
                                
                                {
                                
                                a.setPrice(newPriceForStock);
                                
                                a.setQuantity(quantityForStock);
                                
                                a.setBookValueOne(a.bookValue, newPriceForStock, quantityForStock,0);
                                
                                checker++;
                                
                                JOptionPane.showMessageDialog(null, "Succesfully bought");
                                
                                }
                            }
                        }
                
                    if(checker == 0)
                    
                    {        
                                String stockName;
                                
                                String stockSymbol;
                                
                                int stockQuantity = 0;
                                
                                double stockPrice = 0;
                            
                                //System.out.println("Enter the stock name");
                                
                                stockName = investName;
                                
                                //System.out.println("Enter the symbol");
                                
                                stockSymbol = investSymbol;
                                
                                //System.out.println("Enter the quantity");
                                
                                stockQuantity = Integer.parseInt(investQuantity);
                                
                                //System.out.println("Enter the price");
                                
                                stockPrice = Double.parseDouble(investPrice);
                                
                                //scan.nextLine();
                                
                                if(last == 0)
                                
                                {
                                
                                Mutualfund stocka  = new Mutualfund(stockSymbol,stockName,stockQuantity,stockPrice,0);
                                
                                stocka.setBookValue(0,stockPrice, stockQuantity,0);
                                
                                InvestmentAll.add(stocka);
                                
                                JOptionPane.showMessageDialog(null, "Succesfully bought");
                                
                                }
                                
                    }            
                                
               }
        
        if(last == 0)
        
        {
        
            dispose();
              
            Menu a = new Menu(null, true);
              
            a.setVisible(true);
            
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        jTextField1.setText("");
        
        jTextField2.setText("");
        
        jTextField3.setText("");
        
        jTextField4.setText("");
        
        jComboBox1.setSelectedIndex(0);
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
            dispose();
              
            Menu a = new Menu(null, true);
              
            a.setVisible(true);
            
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyInvestment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyInvestment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyInvestment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyInvestment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuyInvestment dialog = new BuyInvestment(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        
                      
                        
                        System.exit(0);
                        
                       
              
                        
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
